from enum import Enum


class Status(str, Enum):
    MET = "MET"
    PARTIALLY_MET = "PARTIALLY_MET"
    NOT_MET = "NOT_MET"
    UNKNOWN = "UNKNOWN"


class Category(str, Enum):
    LEGAL = "LEGAL"
    FINANCIAL = "FINANCIAL"
    TECHNICAL = "TECHNICAL"
    EXPERIENCE = "EXPERIENCE"
    CERTIFICATION = "CERTIFICATION"
    PERSONNEL = "PERSONNEL"
    DOCUMENTATION = "DOCUMENTATION"
    DELIVERY = "DELIVERY"
    COMMERCIAL = "COMMERCIAL"
    CONTRACTUAL = "CONTRACTUAL"


class MandatoryLevel(str, Enum):
    MANDATORY = "MANDATORY"
    PREFERRED = "PREFERRED"
    INFORMATIONAL = "INFORMATIONAL"
    UNKNOWN = "UNKNOWN"


class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class Recommendation(str, Enum):
    GO = "GO"
    GO_WITH_CONDITIONS = "GO_WITH_CONDITIONS"
    NO_GO = "NO_GO"


class Method(str, Enum):
    DETERMINISTIC_RULE = "DETERMINISTIC_RULE"
    LLM_SEMANTIC = "LLM_SEMANTIC"
    NO_EVIDENCE = "NO_EVIDENCE"


class RuleType(str, Enum):
    MEMBERSHIP = "membership"
    THRESHOLD = "threshold"
    COUNT = "count"
    DATE = "date"
    BOOLEAN = "boolean"
    NONE = "none"  # no measurable rule -> semantic classification


class JobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class ReasonCode(str, Enum):
    ALL_CRITICAL_MANDATORY_MET = "ALL_CRITICAL_MANDATORY_MET"
    MANDATORY_CERTIFICATION_MISSING = "MANDATORY_CERTIFICATION_MISSING"
    MANDATORY_EVIDENCE_UNKNOWN = "MANDATORY_EVIDENCE_UNKNOWN"
    EXPERIENCE_THRESHOLD_NOT_MET = "EXPERIENCE_THRESHOLD_NOT_MET"
    FINANCIAL_THRESHOLD_NOT_MET = "FINANCIAL_THRESHOLD_NOT_MET"
    DOCUMENT_REQUIRED_MISSING = "DOCUMENT_REQUIRED_MISSING"
    DELIVERY_CONSTRAINT_RISK = "DELIVERY_CONSTRAINT_RISK"
    CONFLICTING_TENDER_TERMS = "CONFLICTING_TENDER_TERMS"
    MANDATORY_REQUIREMENT_NOT_MET = "MANDATORY_REQUIREMENT_NOT_MET"
    MANDATORY_PARTIALLY_MET = "MANDATORY_PARTIALLY_MET"
