import type {
  AnalysisSummary,
  RequirementWithResult,
  RiskItem,
  ScoreSnapshot,
} from "@/types";

export const MOCK_ANALYSIS_ID = "mock-demo-001";

export const MOCK_SUMMARY: AnalysisSummary = {
  analysis_id: MOCK_ANALYSIS_ID,
  status: "COMPLETE",
  documents: [
    { document_id: "doc-001", filename: "Tender_RFP_2025_ICT.pdf", pages: 42 },
    { document_id: "doc-002", filename: "Technical_Specifications_v3.pdf", pages: 18 },
    { document_id: "doc-003", filename: "Contractual_Terms_Annex.pdf", pages: 9 },
  ],
  counts: {
    total: 16,
    mandatory: 9,
    MET: 6,
    PARTIALLY_MET: 2,
    NOT_MET: 4,
    UNKNOWN: 4,
  },
  recommendation: "GO_WITH_CONDITIONS",
  final_score: 58.4,
  summary: {
    warnings: [
      "Annual revenue threshold not met by 40%",
      "Company registration documents status unknown",
    ],
    timings: { parsing: 1.2, extraction: 8.4, matching: 3.1, scoring: 0.4 },
    parsing_coverage: 0.96,
    requirement_count: 16,
  },
};

export const MOCK_REQUIREMENTS: RequirementWithResult[] = [
  {
    requirement_id: "REQ-001",
    text: "Supplier must hold a valid ISO 9001:2015 Quality Management System certification.",
    category: "CERTIFICATION",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.97,
    normalized_rule: { rule_type: "membership", field: "certifications", operator: "contains", value: "ISO 9001", filters: {} },
    sources: [
      { document_id: "doc-001", page: 7, section: "4.2 Quality Criteria", excerpt: "All bidders must hold a valid ISO 9001:2015 QMS certification issued by an accredited body." },
    ],
    result: {
      requirement_id: "REQ-001",
      status: "MET",
      method: "DETERMINISTIC_RULE",
      supporting_evidence_ids: ["EVD-001"],
      rationale: "Supplier holds ISO 9001:2015 certification (EVD-001), issued 2025-01-10, valid until 2028-01-09.",
      confidence: 0.99,
      risk_severity: undefined,
      reason_code: undefined,
    },
    evidence_candidates: [
      {
        score: 0.99,
        evidence: {
          evidence_id: "EVD-001",
          type: "CERTIFICATE",
          label: "ISO 9001:2015 Certificate",
          value: "ISO 9001",
          text: "ISO 9001:2015 Quality Management System",
          source: "company_profile",
          issued_date: "2025-01-10",
          expiry_date: "2028-01-09",
          metadata: {},
        },
      },
    ],
  },
  {
    requirement_id: "REQ-002",
    text: "Bidder must demonstrate annual revenue of at least 2,000,000 AZN for the most recent fiscal year.",
    category: "FINANCIAL",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.95,
    normalized_rule: { rule_type: "threshold", field: "annual_revenue", operator: ">=", value: 2000000, unit: "AZN", filters: {} },
    sources: [
      { document_id: "doc-001", page: 11, section: "5.1 Financial Eligibility", excerpt: "Minimum annual turnover of AZN 2,000,000 for the preceding financial year is required." },
    ],
    result: {
      requirement_id: "REQ-002",
      status: "NOT_MET",
      method: "DETERMINISTIC_RULE",
      supporting_evidence_ids: [],
      rationale: "Supplier revenue of 1,200,000 AZN (2025) is 40% below the 2,000,000 AZN threshold.",
      confidence: 0.98,
      risk_severity: "CRITICAL",
      reason_code: "FINANCIAL_THRESHOLD_NOT_MET",
    },
    evidence_candidates: [
      {
        score: 0.91,
        evidence: {
          evidence_id: "EVD-FIN-001",
          type: "FINANCIAL",
          label: "Annual Revenue 2025",
          value: 1200000,
          text: "Annual revenue 2025: AZN 1,200,000",
          source: "company_profile",
          metadata: { currency: "AZN", year: 2025 },
        },
      },
    ],
  },
  {
    requirement_id: "REQ-003",
    text: "The company must have at least 5 years of demonstrated experience in IT infrastructure projects.",
    category: "EXPERIENCE",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.92,
    normalized_rule: { rule_type: "threshold", field: "founded_year", operator: "<=", value: 2020, unit: "year", filters: {} },
    sources: [
      { document_id: "doc-001", page: 13, section: "5.3 Technical Capacity", excerpt: "Bidders must demonstrate no less than five (5) years of continuous operation in the ICT infrastructure sector." },
    ],
    result: {
      requirement_id: "REQ-003",
      status: "PARTIALLY_MET",
      method: "DETERMINISTIC_RULE",
      supporting_evidence_ids: ["EVD-COMPANY-001"],
      rationale: "Company founded in 2018, providing 7 years of operation. However, sector-specific ICT infrastructure projects only verified from 2023.",
      confidence: 0.82,
      risk_severity: "HIGH",
      reason_code: "EXPERIENCE_THRESHOLD_NOT_MET",
    },
    evidence_candidates: [
      {
        score: 0.82,
        evidence: {
          evidence_id: "EVD-COMPANY-001",
          type: "COMPANY_FACT",
          label: "Company Founded Year",
          value: 2018,
          text: "Founded: 2018",
          source: "company_profile",
          metadata: {},
        },
      },
    ],
  },
  {
    requirement_id: "REQ-004",
    text: "Bidder must provide references for at least 5 completed enterprise-scale IT projects each valued above AZN 300,000.",
    category: "EXPERIENCE",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.93,
    normalized_rule: { rule_type: "count", field: "projects", operator: ">=", value: 5, filters: { min_value: 300000, tags: ["enterprise"] } },
    sources: [
      { document_id: "doc-002", page: 4, section: "3.1 Project References", excerpt: "A minimum of five (5) projects of enterprise scope, each with a contract value exceeding AZN 300,000, must be referenced." },
    ],
    result: {
      requirement_id: "REQ-004",
      status: "NOT_MET",
      method: "DETERMINISTIC_RULE",
      supporting_evidence_ids: ["EVD-PROJ-001"],
      rationale: "Only 1 qualifying enterprise project found (AZN 420,000). Requirement demands 5 projects meeting the threshold.",
      confidence: 0.96,
      risk_severity: "HIGH",
      reason_code: "EXPERIENCE_THRESHOLD_NOT_MET",
    },
    evidence_candidates: [
      {
        score: 0.95,
        evidence: {
          evidence_id: "EVD-PROJ-001",
          type: "PROJECT",
          label: "Network Modernization A",
          value: 420000,
          text: "Network Modernization A — AZN 420,000 (2025) — network infrastructure, enterprise",
          source: "company_profile",
          metadata: { year: 2025, currency: "AZN", tags: ["network infrastructure", "enterprise"] },
        },
      },
    ],
  },
  {
    requirement_id: "REQ-005",
    text: "Supplier must provide certified copies of company registration documents from the Ministry of Taxes of Azerbaijan.",
    category: "DOCUMENTATION",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.94,
    normalized_rule: { rule_type: "membership", field: "documents", operator: "contains", value: "company_registration", filters: {} },
    sources: [
      { document_id: "doc-003", page: 2, section: "2.1 Legal Documents", excerpt: "Certified copies of company registration certificate and state tax registration must be attached." },
    ],
    result: {
      requirement_id: "REQ-005",
      status: "UNKNOWN",
      method: "NO_EVIDENCE",
      supporting_evidence_ids: [],
      rationale: "Company registration documents not found in supplier profile. Cannot verify compliance without official documentation.",
      confidence: 0.0,
      risk_severity: "HIGH",
      reason_code: "DOCUMENT_REQUIRED_MISSING",
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-006",
    text: "ISO 27001 Information Security Management certification is required for handling confidential government data.",
    category: "CERTIFICATION",
    mandatory_level: "PREFERRED",
    extraction_confidence: 0.89,
    normalized_rule: { rule_type: "membership", field: "certifications", operator: "contains", value: "ISO 27001", filters: {} },
    sources: [
      { document_id: "doc-002", page: 9, section: "4.4 Security Requirements", excerpt: "Preferred: ISO/IEC 27001 certification for information security management will be given additional evaluation weight." },
    ],
    result: {
      requirement_id: "REQ-006",
      status: "NOT_MET",
      method: "DETERMINISTIC_RULE",
      supporting_evidence_ids: [],
      rationale: "ISO 27001 certification not present in supplier profile. Only ISO 9001 is held.",
      confidence: 0.95,
      risk_severity: "MEDIUM",
      reason_code: "MANDATORY_CERTIFICATION_MISSING",
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-007",
    text: "Bidder must be legally registered in the Republic of Azerbaijan with an active business license.",
    category: "LEGAL",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.99,
    normalized_rule: { rule_type: "boolean", field: "local_presence", operator: "==", value: true, filters: {} },
    sources: [
      { document_id: "doc-001", page: 5, section: "3.1 Eligibility", excerpt: "Only companies registered and operating within the Republic of Azerbaijan are eligible to participate." },
    ],
    result: {
      requirement_id: "REQ-007",
      status: "MET",
      method: "LLM_SEMANTIC",
      supporting_evidence_ids: ["EVD-COMPANY-001"],
      rationale: "CaspianTech LLC is incorporated in Azerbaijan (inferred from company name and profile context).",
      confidence: 0.91,
      risk_severity: undefined,
      reason_code: undefined,
    },
    evidence_candidates: [
      {
        score: 0.88,
        evidence: {
          evidence_id: "EVD-COMPANY-001",
          type: "COMPANY_FACT",
          label: "Company Name",
          value: "CaspianTech LLC",
          text: "CaspianTech LLC",
          source: "company_profile",
          metadata: {},
        },
      },
    ],
  },
  {
    requirement_id: "REQ-008",
    text: "Supplier must demonstrate technical expertise in enterprise network infrastructure design and deployment.",
    category: "TECHNICAL",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.88,
    normalized_rule: { rule_type: "none", filters: {} },
    sources: [
      { document_id: "doc-002", page: 6, section: "3.3 Technical Competencies", excerpt: "Demonstrated capability in enterprise LAN/WAN design, fiber optic deployment, and network security implementation." },
    ],
    result: {
      requirement_id: "REQ-008",
      status: "MET",
      method: "LLM_SEMANTIC",
      supporting_evidence_ids: ["EVD-PROJ-001"],
      rationale: "Network Modernization A project (AZN 420,000) demonstrates enterprise network infrastructure expertise.",
      confidence: 0.85,
      risk_severity: undefined,
      reason_code: undefined,
    },
    evidence_candidates: [
      {
        score: 0.85,
        evidence: {
          evidence_id: "EVD-PROJ-001",
          type: "PROJECT",
          label: "Network Modernization A",
          value: "network infrastructure, enterprise",
          text: "Network Modernization A — enterprise network infrastructure project",
          source: "company_profile",
          metadata: { tags: ["network infrastructure", "enterprise"] },
        },
      },
    ],
  },
  {
    requirement_id: "REQ-009",
    text: "Bidder must demonstrate capacity to provide a performance bond of 10% of contract value.",
    category: "FINANCIAL",
    mandatory_level: "PREFERRED",
    extraction_confidence: 0.86,
    normalized_rule: { rule_type: "none", filters: {} },
    sources: [
      { document_id: "doc-003", page: 6, section: "6.2 Financial Guarantees", excerpt: "A performance bond equivalent to 10% of total contract value is preferred. Bond must be from an accredited bank." },
    ],
    result: {
      requirement_id: "REQ-009",
      status: "UNKNOWN",
      method: "NO_EVIDENCE",
      supporting_evidence_ids: [],
      rationale: "No information on performance bond capacity found in the supplier profile.",
      confidence: 0.0,
      risk_severity: "MEDIUM",
      reason_code: "MANDATORY_EVIDENCE_UNKNOWN",
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-010",
    text: "Bidding company must employ at least 50 full-time staff members.",
    category: "PERSONNEL",
    mandatory_level: "PREFERRED",
    extraction_confidence: 0.91,
    normalized_rule: { rule_type: "threshold", field: "employees", operator: ">=", value: 50, filters: {} },
    sources: [
      { document_id: "doc-001", page: 15, section: "5.4 Organizational Capacity", excerpt: "Preferred suppliers have a minimum workforce of 50 full-time employees to ensure project delivery capacity." },
    ],
    result: {
      requirement_id: "REQ-010",
      status: "NOT_MET",
      method: "DETERMINISTIC_RULE",
      supporting_evidence_ids: ["EVD-EMPLOYEES-001"],
      rationale: "Supplier has 42 employees, which is below the preferred threshold of 50.",
      confidence: 0.99,
      risk_severity: "MEDIUM",
      reason_code: "MANDATORY_REQUIREMENT_NOT_MET",
    },
    evidence_candidates: [
      {
        score: 0.99,
        evidence: {
          evidence_id: "EVD-EMPLOYEES-001",
          type: "COMPANY_FACT",
          label: "Employee Count",
          value: 42,
          text: "42 full-time employees",
          source: "company_profile",
          metadata: {},
        },
      },
    ],
  },
  {
    requirement_id: "REQ-011",
    text: "Project Manager must hold PMP or PRINCE2 certification.",
    category: "PERSONNEL",
    mandatory_level: "PREFERRED",
    extraction_confidence: 0.87,
    normalized_rule: { rule_type: "none", filters: {} },
    sources: [
      { document_id: "doc-002", page: 12, section: "4.1 Key Personnel", excerpt: "The designated Project Manager should hold an internationally recognized PM certification such as PMP or PRINCE2." },
    ],
    result: {
      requirement_id: "REQ-011",
      status: "UNKNOWN",
      method: "NO_EVIDENCE",
      supporting_evidence_ids: [],
      rationale: "No information about Project Manager qualifications found in the supplier profile.",
      confidence: 0.0,
      risk_severity: "LOW",
      reason_code: "MANDATORY_EVIDENCE_UNKNOWN",
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-012",
    text: "Complete project delivery must be achieved within 90 calendar days from contract signing.",
    category: "DELIVERY",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.96,
    normalized_rule: { rule_type: "threshold", field: "delivery_days", operator: "<=", value: 90, unit: "days", filters: {} },
    sources: [
      { document_id: "doc-003", page: 4, section: "5.1 Delivery Timeline", excerpt: "The entire scope of work must be completed and accepted within ninety (90) calendar days of contract commencement." },
    ],
    result: {
      requirement_id: "REQ-012",
      status: "MET",
      method: "LLM_SEMANTIC",
      supporting_evidence_ids: ["EVD-PROJ-001"],
      rationale: "Past project (Network Modernization A) demonstrates ability to deliver infrastructure projects within standard timelines.",
      confidence: 0.75,
      risk_severity: undefined,
      reason_code: undefined,
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-013",
    text: "Supplier must accept fixed-price lump-sum contract structure with no price escalation clauses.",
    category: "CONTRACTUAL",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.93,
    normalized_rule: { rule_type: "none", filters: {} },
    sources: [
      { document_id: "doc-003", page: 8, section: "7.1 Contract Type", excerpt: "This procurement is conducted on a fixed-price basis. No price adjustment or escalation clauses will be considered." },
    ],
    result: {
      requirement_id: "REQ-013",
      status: "MET",
      method: "LLM_SEMANTIC",
      supporting_evidence_ids: [],
      rationale: "No contractual restrictions in supplier profile that would prevent acceptance of fixed-price terms.",
      confidence: 0.78,
      risk_severity: undefined,
      reason_code: undefined,
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-014",
    text: "Bidder must offer a minimum 2-year warranty and post-delivery support for all installed equipment.",
    category: "COMMERCIAL",
    mandatory_level: "PREFERRED",
    extraction_confidence: 0.84,
    normalized_rule: { rule_type: "threshold", field: "warranty_years", operator: ">=", value: 2, unit: "years", filters: {} },
    sources: [
      { document_id: "doc-002", page: 17, section: "6.3 Post-Delivery Support", excerpt: "Preferred: A minimum warranty period of 24 months with SLA-backed technical support." },
    ],
    result: {
      requirement_id: "REQ-014",
      status: "PARTIALLY_MET",
      method: "LLM_SEMANTIC",
      supporting_evidence_ids: ["EVD-PROJ-001"],
      rationale: "Past project indicates support was provided, but explicit 2-year warranty commitment not documented in profile.",
      confidence: 0.62,
      risk_severity: "LOW",
      reason_code: "MANDATORY_PARTIALLY_MET",
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-015",
    text: "All technical documentation, manuals, and reports must be delivered in the Azerbaijani language.",
    category: "DOCUMENTATION",
    mandatory_level: "INFORMATIONAL",
    extraction_confidence: 0.88,
    normalized_rule: { rule_type: "none", filters: {} },
    sources: [
      { document_id: "doc-003", page: 9, section: "8.2 Language Requirements", excerpt: "All deliverable documentation shall be prepared in the Azerbaijani state language (Azerbaijani/Azeri)." },
    ],
    result: {
      requirement_id: "REQ-015",
      status: "UNKNOWN",
      method: "NO_EVIDENCE",
      supporting_evidence_ids: [],
      rationale: "No information about language capability in the supplier profile.",
      confidence: 0.0,
      risk_severity: "LOW",
      reason_code: "MANDATORY_EVIDENCE_UNKNOWN",
    },
    evidence_candidates: [],
  },
  {
    requirement_id: "REQ-016",
    text: "Supplier must not have any pending litigation or unresolved tax disputes with government entities.",
    category: "LEGAL",
    mandatory_level: "MANDATORY",
    extraction_confidence: 0.92,
    normalized_rule: { rule_type: "boolean", field: "litigation_clear", operator: "==", value: true, filters: {} },
    sources: [
      { document_id: "doc-001", page: 8, section: "4.3 Legal Standing", excerpt: "Bidder must provide a declaration that no litigation, arbitration or tax disputes with governmental bodies are pending." },
    ],
    result: {
      requirement_id: "REQ-016",
      status: "MET",
      method: "LLM_SEMANTIC",
      supporting_evidence_ids: [],
      rationale: "No adverse legal information found in supplier profile. Clean standing assumed unless evidence contradicts.",
      confidence: 0.7,
      risk_severity: undefined,
      reason_code: undefined,
    },
    evidence_candidates: [],
  },
];

export const MOCK_RISKS: RiskItem[] = [
  {
    requirement_id: "REQ-002",
    severity: "CRITICAL",
    explanation: "Annual revenue of AZN 1,200,000 is 40% below the mandatory threshold of AZN 2,000,000. This is a hard disqualification criterion. Failing to meet this will result in automatic rejection during administrative review.",
    recommended_action: "Provide audited financial statements demonstrating consolidated revenue or explore consortium bidding with a qualified financial partner to meet the threshold.",
    reason_code: "FINANCIAL_THRESHOLD_NOT_MET",
  },
  {
    requirement_id: "REQ-004",
    severity: "HIGH",
    explanation: "Only 1 of the required 5 enterprise project references meeting the AZN 300,000 value threshold could be verified. This represents a significant gap in demonstrated delivery capacity.",
    recommended_action: "Compile and document all completed enterprise projects. Include sub-contracts, joint ventures, or projects completed under previous company structures if applicable.",
    reason_code: "EXPERIENCE_THRESHOLD_NOT_MET",
  },
  {
    requirement_id: "REQ-005",
    severity: "HIGH",
    explanation: "Company registration documents are not present in the supplier profile, making compliance status UNKNOWN. These are mandatory submission documents and their absence will cause the bid to be declared incomplete.",
    recommended_action: "Obtain certified copies of company registration certificate and tax registration from the Ministry of Taxes of Azerbaijan immediately. Upload to supplier profile.",
    reason_code: "DOCUMENT_REQUIRED_MISSING",
  },
  {
    requirement_id: "REQ-003",
    severity: "HIGH",
    explanation: "While the company has been registered since 2018, verifiable sector-specific ICT infrastructure project evidence only covers 3 years. The requirement demands 5 continuous years of ICT infrastructure experience.",
    recommended_action: "Prepare a detailed company history document highlighting ICT infrastructure work from 2018-2022. Obtain client letters of reference or contracts to substantiate early-stage project experience.",
    reason_code: "EXPERIENCE_THRESHOLD_NOT_MET",
  },
];

export const MOCK_SCORE: ScoreSnapshot = {
  dimensions: [
    { name: "Legal", weight: 0.15, score: 0.85, coverage: 1.0, requirement_count: 2 },
    { name: "Financial", weight: 0.25, score: 0.25, coverage: 1.0, requirement_count: 2 },
    { name: "Technical", weight: 0.20, score: 0.8, coverage: 1.0, requirement_count: 1 },
    { name: "Experience", weight: 0.20, score: 0.25, coverage: 1.0, requirement_count: 2 },
    { name: "Certification", weight: 0.10, score: 0.5, coverage: 1.0, requirement_count: 2 },
    { name: "Personnel", weight: 0.05, score: 0.2, coverage: 0.5, requirement_count: 2 },
    { name: "Documentation", weight: 0.05, score: 0.25, coverage: 0.5, requirement_count: 2 },
  ],
  final_score: 58.4,
  recommendation: "GO_WITH_CONDITIONS",
  reason_codes: ["FINANCIAL_THRESHOLD_NOT_MET", "EXPERIENCE_THRESHOLD_NOT_MET", "DOCUMENT_REQUIRED_MISSING"],
  overall_coverage: 0.75,
  config: {
    status_points: { MET: 100, PARTIALLY_MET: 50, NOT_MET: 0, UNKNOWN: 0 },
    go_threshold: 75,
    no_go_threshold: 40,
  },
};

// Simulate async delay
export const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));
